from pathlib import Path
p = Path('/home/ubuntu/faj2ni/client/src/pages/Admin.tsx')
s = p.read_text()
s = s.replace('<span style={{ color: "var(--muted)", fontSize: 11 }}>السعر المدفوع: {formatJOD(data.budgetFils)}</span>', '')
s = s.replace('value={salePrice / 1000} onChange={event => setSalePrice(Number(event.target.value) * 1000)}', 'min={0} value={salePrice / 1000} onChange={event => setSalePrice(Math.max(0, Number(event.target.value)) * 1000)}')
s = s.replace('value={deliveryFils / 1000} onChange={event => setDeliveryFils(Number(event.target.value) * 1000)}', 'min={0} value={deliveryFils / 1000} onChange={event => setDeliveryFils(Math.max(0, Number(event.target.value)) * 1000)}')
s = s.replace('value={item.quantity} onChange={event => { const copy = [...items]; copy[index].quantity = Number(event.target.value); setItems(copy); }} placeholder="الكمية"', 'min={0} value={item.quantity} onChange={event => { const copy = [...items]; copy[index].quantity = Math.max(0, Number(event.target.value)); setItems(copy); }} placeholder="الكمية"')
s = s.replace('value={item.unitCostFils / 1000} onChange={event => { const copy = [...items]; copy[index].unitCostFils = Number(event.target.value) * 1000; setItems(copy); }} placeholder="تكلفة الوحدة بالدينار"', 'min={0} value={item.unitCostFils / 1000} onChange={event => { const copy = [...items]; copy[index].unitCostFils = Math.max(0, Number(event.target.value)) * 1000; setItems(copy); }} placeholder="تكلفة الوحدة بالدينار"')
s = s.replace('<div className="field"><input value={item.name}', '<div className="field"><label>اسم المنتج</label><input value={item.name}')
s = s.replace('<div className="field"><input type="number" min={0} value={item.quantity}', '<div className="field"><label>الكمية</label><input type="number" min={0} value={item.quantity}')
s = s.replace('<div className="field span-2"><input type="number" min={0} value={item.unitCostFils', '<div className="field span-2"><label>تكلفة الوحدة (د.أ)</label><input type="number" min={0} value={item.unitCostFils')
s = s.replace('const updateCost = (key: keyof typeof costs, value: number) => setCosts({ ...costs, [key]: value * 1000 });', 'const updateCost = (key: keyof typeof costs, value: number) => setCosts({ ...costs, [key]: Math.max(0, value) * 1000 });')
s = s.replace('value={costs[key as keyof typeof costs] / 1000} onChange={event => updateCost(key as keyof typeof costs, Number(event.target.value))}', 'min={0} value={costs[key as keyof typeof costs] / 1000} onChange={event => updateCost(key as keyof typeof costs, Number(event.target.value))}')
p.write_text(s)
