import { ArrowLeft, ClipboardList, Loader2, LogIn, LockKeyhole, UserRound, XCircle } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { contrastText, dateAr, formatJOD, StatusBadge, userErrorMessage } from "@/lib/faj2ni";

function AccountHeader({ authenticated, onLogout }: { authenticated: boolean; onLogout?: () => void }) {
  return <header className="site-header"><div className="container-f header-row"><Link href="/" className="brand"><span className="brand-mark"><UserRound size={17} /></span><span>فاجئني</span></Link><div className="header-actions"><Link href="/create-order" className="btn btn-primary">أنشئ طلبًا <ArrowLeft size={15} /></Link>{authenticated && <button className="btn btn-outline" onClick={onLogout}>تسجيل الخروج</button>}</div></div></header>;
}

export default function Account() {
  const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const utils = trpc.useUtils();
  const { data: account, isLoading } = trpc.customer.me.useQuery(); const { data: storefront } = trpc.storefront.bootstrap.useQuery(); const values = storefront?.settings ?? {};
  const themeStyle = { "--primary": values.primaryColor || "#6c5ce7", "--primary-foreground": contrastText(values.primaryColor || "#6c5ce7"), "--secondary": values.secondaryColor || "#f2b5d4", "--canvas": values.backgroundColor || "#fcfbff", "--ink": contrastText(values.backgroundColor || "#fcfbff"), "--muted": contrastText(values.backgroundColor || "#fcfbff") === "#ffffff" ? "#ded9e8" : "#6f6981", "--radius": `${values.borderRadius || "18"}px` } as React.CSSProperties;
  const login = trpc.customer.login.useMutation({ onSuccess: async () => { await utils.customer.me.invalidate(); toast.success("أهلًا بك مجددًا"); }, onError: error => toast.error(userErrorMessage(error)) });
  const logout = trpc.customer.logout.useMutation({ onSuccess: async () => { await utils.customer.me.invalidate(); toast.success("تم تسجيل الخروج."); } });
  const cancel = trpc.customer.cancelOrder.useMutation({ onSuccess: async () => { toast.success("تم إلغاء الطلب."); await utils.customer.me.invalidate(); }, onError: error => toast.error(userErrorMessage(error)) });
  if (isLoading) return <div className="page-shell" style={themeStyle}><AccountHeader authenticated={false} /><main className="flow-page"><div className="account-shell"><div className="shimmer-card" /><div className="shimmer-card" /></div></main></div>;
  if (!account) return <div className="page-shell" style={themeStyle}><AccountHeader authenticated={false} /><main className="flow-page"><div className="container-f"><div className="account-card login-card"><span className="category-icon"><UserRound /></span><h1 style={{ fontSize: 26, letterSpacing: "-.05em" }}>حسابي</h1><p className="section-subtitle">ادخل برقم هاتفك وكلمة المرور لمتابعة طلباتك السابقة.</p><div className="field" style={{ marginTop: 20 }}><label>رقم الهاتف</label><input value={phone} onChange={event => setPhone(event.target.value)} inputMode="tel" placeholder="07XXXXXXXX" /></div><div className="field" style={{ marginTop: 14 }}><label>كلمة المرور</label><input value={password} onChange={event => setPassword(event.target.value)} type="password" autoComplete="current-password" placeholder="6 أحرف أو أرقام على الأقل" /><span className="help">تختار كلمة المرور عند إنشاء أول طلب.</span></div><div style={{ marginTop: 20 }}><button className="btn btn-primary" disabled={login.isPending} onClick={() => login.mutate({ phone, password })}>{login.isPending ? <Loader2 className="animate-spin" size={16} /> : <LogIn size={16} />} دخول</button></div><div className="help" style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 6 }}><LockKeyhole size={14} /> لا توجد خدمة SMS؛ الدخول يتم بكلمة المرور فقط.</div></div></div></main></div>;
  return <div className="page-shell" style={themeStyle}><AccountHeader authenticated onLogout={() => logout.mutate()} /><main className="flow-page"><div className="account-shell"><div className="profile-card"><div className="section-kicker">حساب العميل</div><h1>{account.customer.fullName}</h1><div className="profile-phone" dir="ltr">{account.customer.phone}</div></div><div className="account-card"><div className="account-heading"><div><div className="section-kicker">سجل الطلبات</div><h2>طلباتك السابقة</h2></div><ClipboardList size={20} color="var(--primary)" /></div>{account.orders.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>رقم الطلب</th><th>الفئة</th><th>الميزانية</th><th>التوصيل</th><th>التاريخ</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{account.orders.map(order => <tr key={order.id}><td dir="ltr"><Link className="row-link" href={`/account/orders/${order.id}`}>{order.orderNumber}</Link></td><td>{order.categoryName}</td><td>{formatJOD(order.budgetFils)}</td><td>{formatJOD(order.deliveryFils)}</td><td>{dateAr(order.createdAt)}</td><td><StatusBadge status={order.status} /></td><td>{order.status === "NEW" ? <button className="btn btn-danger btn-sm" disabled={cancel.isPending} onClick={() => { if (window.confirm("هل تريد إلغاء هذا الطلب؟")) cancel.mutate({ orderId: order.id }); }}><XCircle size={14} /> إلغاء</button> : <Link className="btn btn-soft btn-sm" href={`/account/orders/${order.id}`}>التفاصيل</Link>}</td></tr>)}</tbody></table></div> : <div className="empty-state">لا توجد طلبات مرتبطة بهذا الرقم بعد.</div>}</div></div></main></div>;
}
