import { ArrowRight, ClipboardList, Loader2, MapPin, PackageCheck, Truck } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { contrastText, dateAr, formatJOD, StatusBadge, userErrorMessage } from "@/lib/faj2ni";

export default function CustomerOrderDetail({ id }: { id: number }) {
  const { data: order, isLoading, error } = trpc.customer.orderDetail.useQuery({ orderId: id });
  const { data: storefront } = trpc.storefront.bootstrap.useQuery();
  const values = storefront?.settings ?? {};
  const themeStyle = { "--primary": values.primaryColor || "#6c5ce7", "--primary-foreground": contrastText(values.primaryColor || "#6c5ce7"), "--secondary": values.secondaryColor || "#f2b5d4", "--canvas": values.backgroundColor || "#fcfbff", "--ink": contrastText(values.backgroundColor || "#fcfbff"), "--muted": contrastText(values.backgroundColor || "#fcfbff") === "#ffffff" ? "#ded9e8" : "#6f6981", "--radius": `${values.borderRadius || "18"}px` } as React.CSSProperties;
  if (isLoading) return <div className="page-shell" style={themeStyle}><header className="site-header"><div className="container-f header-row"><Link href="/account" className="brand">فاجئني</Link></div></header><main className="flow-page"><div className="shimmer-card" /></main></div>;
  if (error || !order) return <div className="page-shell" style={themeStyle}><header className="site-header"><div className="container-f header-row"><Link href="/account" className="brand">فاجئني</Link></div></header><main className="flow-page"><div className="container-f"><div className="error-banner">{userErrorMessage(error ?? { message: "NOT_FOUND" })}</div><Link href="/account" className="btn btn-outline" style={{ marginTop: 16 }}><ArrowRight size={16} /> العودة للحساب</Link></div></main></div>;
  return <div className="page-shell" style={themeStyle}><header className="site-header"><div className="container-f header-row"><Link href="/account" className="brand">فاجئني</Link><Link href="/account" className="btn btn-outline"><ArrowRight size={15} /> حسابي</Link></div></header><main className="flow-page"><div className="account-shell"><Link href="/account" className="btn btn-outline btn-sm"><ArrowRight size={14} /> العودة لطلباتي</Link><div className="account-card" style={{ marginTop: 16 }}><div className="account-heading"><div><div className="section-kicker">تفاصيل الطلب</div><h2 dir="ltr">{order.orderNumber}</h2></div><StatusBadge status={order.status} /></div><div className="detail-summary-grid"><div><ClipboardList size={17} /><span>الفئة</span><strong>{order.categoryName}</strong></div><div><PackageCheck size={17} /><span>الميزانية</span><strong>{formatJOD(order.budgetFils)}</strong></div><div><Truck size={17} /><span>تكلفة التوصيل</span><strong>{formatJOD(order.deliveryFils)}</strong></div><div><span>تاريخ الطلب</span><strong>{dateAr(order.createdAt)}</strong></div></div></div><div className="account-card"><div className="panel-title"><h2>بيانات التوصيل</h2><MapPin size={19} color="var(--primary)" /></div><div className="info-list"><div><span>المحافظة</span><strong>{order.governorate}</strong></div><div><span>العنوان بالتفصيل</span><strong>{order.address}</strong></div></div></div><div className="account-card"><div className="panel-title"><h2>تتبع الطلب</h2></div><div className="timeline">{order.history.map(item => <div className="timeline-item" key={item.id}><span className="timeline-dot" /><div><strong><StatusBadge status={item.toStatus} /></strong><p>{item.changedBy} · {dateAr(item.createdAt)}</p></div></div>)}</div></div></div></main></div>;
}
